---
#First of all configure VM's
- name: Boot Infra
  hosts: odin
  remote_user: vagrant
  become: yes

  roles:
    - common

#Only master machine uses Jenkins and SonarQube
- name:
  hosts: master
  remote_user: vagrant
  become: yes

  roles:
    - java
    - postgresql
    - sonarqube
    - jenkins

#Use all virtual machine. Make sure that you configured hosts file for kubernetes_role.
- name: Kubernetes
  hosts: odin
  remote_user: vagrant
  become: yes

  roles:
    - docker
    - kubernetes
    - helm